name: GitHub Actions Demo
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        checks: [ 'make flake8', 'make mypy', 'make bandit', 'make safety', 'make test' ]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.9.6
          cache: 'pip'

#      - uses: actions/cache@v3
#        id: requirements_cache
#        with:
#          path: ~/.cache/pip
#          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements**.txt') }}
#          restore-keys: |
#            ${{ runner.os }}-pip-

      - name: Install dependencies
#        if: steps.requirements_cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install -U pip setuptools
          python -m pip install -r requirements-dev.txt

      - name: Run checks
        id: run_checks
        run: make flake8
