name: GitHub Actions Demo
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        checks: [ 'make flake8', 'make mypy', 'make bandit', 'make safety', 'make test' ]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.9.6

#      - uses: actions/cache@v3
#        id: requirements_cache
#        with:
#          path: ~/.cache/pip
#          key: ${{ runner.os }}-pip-${{ hashFiles('requirements**.txt') }}
#          restore-keys: |
#            ${{ runner.os }}-pip-
      - uses: actions/cache@v3
        id: python_cache
        with:
          path: venv
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements**.txt') }}

      - name: Install dependencies
        if: steps.python_cache.outputs.cache-hit != 'true'
        run: |
          if [ -d "venv" ]; then rm -rf venv; fi
          python3 -m venv venv
          venv/bin/python3 -m pip install -U pip setuptools
          venv/bin/python3 -m pip install -r requirements-dev.txt

      - name: Run checks
        id: run_checks
        run: make flake8
